### PR TITLE
Adding Basil Poledouris - Conan the Barbarian

### PR DESCRIPTION
**Pull request by repejota**
Best epic soundtrack ever. :)

### CODE REVIEW

**Comment by mmoreram** [comment]
Didn't know! Let's listen that one!

**Comment by rais38** [comment]
Let's go to listen... Thanks @repejota

**Comment by mmoreram** [comment]
:+1:

**Comment by rais38** [comment]
@repejota can you change the order of links?

1 - `Spotify`
2 - `iTunes`
3 - `Grooveshark`

You can a example [here](https://github.com/friends-of-soundtracks/best-soundtracks/pull/3/files)

**Comment by JMPergar** [comment]
:+1: to Soundtrack, but... I don't believe that you didn't know this OST @mmoreram!!! :-1: for you XD

**Comment by mmoreram** [comment]
@JMPergar :dancer:

**Comment by rais38** [comment]
For me it's ok too but i prefer other order in links but i could change it in other PR.

**Pull request merged**
