### PR TITLE
Added Vangelis

### PR DESCRIPTION
**Pull request by rais38**

### CODE REVIEW

**Comment by mmoreram** [comment]
JOJO, that's it dude :)

Could you please add the artist in the menu?

btw, :+1:

**Comment by rais38** [comment]
@friends-of-soundtracks/maintainers I changed the order so that iTunes is before

**Comment by mmoreram** [comment]
@friends-of-soundtracks/maintainers good! Need your votes!

**Comment by rais38** [comment]
Done @mmoreram in 9893886

**Comment by rais38** [comment]
LGTM (obviously :P)

[LGTM](http://www.lgtm.in/i/Y49aeqX1q)

**Comment by rais38** [comment]
@jmpergar what you think?

**Comment by mmoreram** [comment]
ping @jmpergar Do you want to participate?

**Comment by rais38** [comment]
@jmpergar this PR have your ok? xD

**Comment by rais38** [comment]
@friends-of-soundtracks/maintainers updated PR.

**Comment by JMPergar** [comment]
:+1:

**Pull request merged**
