### PR TITLE
Some must listen

### PR DESCRIPTION
**Pull request by JMPergar**
Man of steel, The holiday, The da vinci code, the last samurai, Inception, A beautiful mind, Avatar, Braveheart, Bicentennial Man

[Review on Reviewable](https://reviewable.io/reviews/friends-of-soundtracks/best-soundtracks/5)

### CODE REVIEW

**Comment by JMPergar** [comment]
@mmoreram @rais38 give me some love!

**Comment by mmoreram** [comment]
Every single one you are saying MUST be here :)

PR with all  of them?

**Comment by rais38** [comment]
Some things:
- `The Dark Knight` is duplicated
- Add link to `iTunes` or `Grooveshark`

If you want, I can be responsible to adds links to `iTunes`, I don't care :D

**Comment by mmoreram** [comment]
Okay, @rais38 responsible of itunes, great.

I'll be responsible for Spotify!

**Comment by rais38** [comment]
@mmoreram great but at least, in each RP, add a source that may be several of the same film.

**Comment by JMPergar** [comment]
I think that we should add at least one link, if other know more PR and go!

**Comment by JMPergar** [comment]
@rais38 fixed!

**Comment by rais38** [comment]
@JMPergar fix conflicts prior to merger.

**Comment by JMPergar** [comment]
@rais38 @mmoreram Merge!!!

**Comment by rais38** [comment]
@JMPergar this PR not be resolved yet

**Pull request closed without merging**
